# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'guimVpiYu.ui'
##
## Created by: Qt User Interface Compiler version 6.11.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QLabel,
    QMainWindow, QSizePolicy, QWidget)

from dbhoverslider import DbHoverSlider
from pyqtgraph import PlotWidget
from spinner import WaitingSpinner

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(820, 440)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(820, 440))
        MainWindow.setMaximumSize(QSize(820, 440))
        MainWindow.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        MainWindow.setAcceptDrops(False)
        MainWindow.setWindowTitle(u"X4-Equalizer")
        icon = QIcon()
        icon.addFile(u"logo.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAccessibleIdentifier(u"")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setLocale(QLocale(QLocale.English, QLocale.Australia))
        MainWindow.setWindowFilePath(u"")
        MainWindow.setIconSize(QSize(16, 16))
        MainWindow.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonFollowStyle)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalSlider_1 = DbHoverSlider(self.centralwidget)
        self.verticalSlider_1.setObjectName(u"verticalSlider_1")
        self.verticalSlider_1.setGeometry(QRect(70, 70, 20, 261))
        self.verticalSlider_1.setToolTipDuration(-10)
        self.verticalSlider_1.setMinimum(-90)
        self.verticalSlider_1.setMaximum(90)
        self.verticalSlider_1.setSingleStep(1)
        self.verticalSlider_1.setPageStep(0)
        self.verticalSlider_1.setOrientation(Qt.Orientation.Vertical)
        self.verticalSlider_2 = DbHoverSlider(self.centralwidget)
        self.verticalSlider_2.setObjectName(u"verticalSlider_2")
        self.verticalSlider_2.setGeometry(QRect(130, 70, 20, 261))
        self.verticalSlider_2.setMinimum(-90)
        self.verticalSlider_2.setMaximum(90)
        self.verticalSlider_2.setSingleStep(0)
        self.verticalSlider_2.setPageStep(0)
        self.verticalSlider_2.setOrientation(Qt.Orientation.Vertical)
        self.verticalSlider_3 = DbHoverSlider(self.centralwidget)
        self.verticalSlider_3.setObjectName(u"verticalSlider_3")
        self.verticalSlider_3.setGeometry(QRect(190, 70, 20, 261))
        self.verticalSlider_3.setMinimum(-90)
        self.verticalSlider_3.setMaximum(90)
        self.verticalSlider_3.setSingleStep(0)
        self.verticalSlider_3.setPageStep(0)
        self.verticalSlider_3.setOrientation(Qt.Orientation.Vertical)
        self.verticalSlider_4 = DbHoverSlider(self.centralwidget)
        self.verticalSlider_4.setObjectName(u"verticalSlider_4")
        self.verticalSlider_4.setGeometry(QRect(250, 70, 20, 261))
        self.verticalSlider_4.setMinimum(-90)
        self.verticalSlider_4.setMaximum(90)
        self.verticalSlider_4.setSingleStep(0)
        self.verticalSlider_4.setPageStep(0)
        self.verticalSlider_4.setOrientation(Qt.Orientation.Vertical)
        self.verticalSlider_5 = DbHoverSlider(self.centralwidget)
        self.verticalSlider_5.setObjectName(u"verticalSlider_5")
        self.verticalSlider_5.setGeometry(QRect(310, 70, 20, 261))
        self.verticalSlider_5.setMinimum(-90)
        self.verticalSlider_5.setMaximum(90)
        self.verticalSlider_5.setSingleStep(0)
        self.verticalSlider_5.setPageStep(0)
        self.verticalSlider_5.setOrientation(Qt.Orientation.Vertical)
        self.verticalSlider_6 = DbHoverSlider(self.centralwidget)
        self.verticalSlider_6.setObjectName(u"verticalSlider_6")
        self.verticalSlider_6.setGeometry(QRect(370, 70, 20, 261))
        self.verticalSlider_6.setMinimum(-90)
        self.verticalSlider_6.setMaximum(90)
        self.verticalSlider_6.setSingleStep(0)
        self.verticalSlider_6.setPageStep(0)
        self.verticalSlider_6.setOrientation(Qt.Orientation.Vertical)
        self.verticalSlider_7 = DbHoverSlider(self.centralwidget)
        self.verticalSlider_7.setObjectName(u"verticalSlider_7")
        self.verticalSlider_7.setGeometry(QRect(430, 70, 20, 261))
        self.verticalSlider_7.setMinimum(-90)
        self.verticalSlider_7.setMaximum(90)
        self.verticalSlider_7.setSingleStep(0)
        self.verticalSlider_7.setPageStep(0)
        self.verticalSlider_7.setOrientation(Qt.Orientation.Vertical)
        self.verticalSlider_8 = DbHoverSlider(self.centralwidget)
        self.verticalSlider_8.setObjectName(u"verticalSlider_8")
        self.verticalSlider_8.setGeometry(QRect(490, 70, 20, 261))
        self.verticalSlider_8.setMinimum(-90)
        self.verticalSlider_8.setMaximum(90)
        self.verticalSlider_8.setSingleStep(0)
        self.verticalSlider_8.setPageStep(0)
        self.verticalSlider_8.setOrientation(Qt.Orientation.Vertical)
        self.verticalSlider_9 = DbHoverSlider(self.centralwidget)
        self.verticalSlider_9.setObjectName(u"verticalSlider_9")
        self.verticalSlider_9.setGeometry(QRect(550, 70, 20, 261))
        self.verticalSlider_9.setMinimum(-90)
        self.verticalSlider_9.setMaximum(90)
        self.verticalSlider_9.setSingleStep(0)
        self.verticalSlider_9.setPageStep(0)
        self.verticalSlider_9.setOrientation(Qt.Orientation.Vertical)
        self.verticalSlider_10 = DbHoverSlider(self.centralwidget)
        self.verticalSlider_10.setObjectName(u"verticalSlider_10")
        self.verticalSlider_10.setGeometry(QRect(610, 70, 20, 261))
        self.verticalSlider_10.setMinimum(-90)
        self.verticalSlider_10.setMaximum(90)
        self.verticalSlider_10.setSingleStep(0)
        self.verticalSlider_10.setPageStep(0)
        self.verticalSlider_10.setOrientation(Qt.Orientation.Vertical)
        self.verticalSlider_preamp = DbHoverSlider(self.centralwidget)
        self.verticalSlider_preamp.setObjectName(u"verticalSlider_preamp")
        self.verticalSlider_preamp.setGeometry(QRect(710, 70, 20, 261))
        self.verticalSlider_preamp.setMinimum(-120)
        self.verticalSlider_preamp.setMaximum(120)
        self.verticalSlider_preamp.setSingleStep(0)
        self.verticalSlider_preamp.setPageStep(0)
        self.verticalSlider_preamp.setOrientation(Qt.Orientation.Vertical)
        self.label_preamp = QLabel(self.centralwidget)
        self.label_preamp.setObjectName(u"label_preamp")
        self.label_preamp.setGeometry(QRect(690, 330, 71, 41))
        font = QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_preamp.setFont(font)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(60, 190, 681, 20))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.EqView = PlotWidget(self.centralwidget)
        self.EqView.setObjectName(u"EqView")
        self.EqView.setGeometry(QRect(20, 40, 641, 321))
        self.comboBox_eq = QComboBox(self.centralwidget)
        self.comboBox_eq.addItem("")
        self.comboBox_eq.addItem("")
        self.comboBox_eq.addItem("")
        self.comboBox_eq.setObjectName(u"comboBox_eq")
        self.comboBox_eq.setGeometry(QRect(20, 380, 111, 32))
        self.comboBox_sphp = QComboBox(self.centralwidget)
        self.comboBox_sphp.addItem("")
        self.comboBox_sphp.addItem("")
        self.comboBox_sphp.setObjectName(u"comboBox_sphp")
        self.comboBox_sphp.setGeometry(QRect(160, 380, 131, 32))
        self.comboBox_eqonoff = QComboBox(self.centralwidget)
        self.comboBox_eqonoff.addItem("")
        self.comboBox_eqonoff.addItem("")
        self.comboBox_eqonoff.setObjectName(u"comboBox_eqonoff")
        self.comboBox_eqonoff.setGeometry(QRect(320, 380, 121, 32))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(60, 340, 41, 18))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(120, 340, 31, 18))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 310, 31, 18))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 190, 31, 18))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 70, 31, 18))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(740, 70, 58, 18))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(740, 310, 58, 18))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(180, 340, 41, 18))
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(240, 340, 41, 18))
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(300, 340, 58, 18))
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(360, 340, 31, 18))
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(420, 340, 31, 18))
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(480, 340, 31, 18))
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(540, 340, 31, 18))
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(600, 340, 41, 18))
        self.waitingspinner = WaitingSpinner(self.centralwidget)
        self.waitingspinner.setObjectName(u"waitingspinner")
        self.waitingspinner.setGeometry(QRect(460, 370, 331, 51))
        MainWindow.setCentralWidget(self.centralwidget)
        self.EqView.raise_()
        self.label_preamp.raise_()
        self.line.raise_()
        self.verticalSlider_preamp.raise_()
        self.verticalSlider_10.raise_()
        self.verticalSlider_9.raise_()
        self.verticalSlider_8.raise_()
        self.verticalSlider_7.raise_()
        self.verticalSlider_6.raise_()
        self.verticalSlider_5.raise_()
        self.verticalSlider_4.raise_()
        self.verticalSlider_2.raise_()
        self.verticalSlider_1.raise_()
        self.comboBox_eq.raise_()
        self.comboBox_sphp.raise_()
        self.comboBox_eqonoff.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.verticalSlider_3.raise_()
        self.waitingspinner.raise_()

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
#if QT_CONFIG(accessibility)
        MainWindow.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(statustip)
        self.verticalSlider_1.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.label_preamp.setText(QCoreApplication.translate("MainWindow", u"Preamp", None))
        self.comboBox_eq.setItemText(0, QCoreApplication.translate("MainWindow", u"Equalizer 1", None))
        self.comboBox_eq.setItemText(1, QCoreApplication.translate("MainWindow", u"Equalizer 2", None))
        self.comboBox_eq.setItemText(2, QCoreApplication.translate("MainWindow", u"Equalizer 3", None))

        self.comboBox_sphp.setItemText(0, QCoreApplication.translate("MainWindow", u"Speakers", None))
        self.comboBox_sphp.setItemText(1, QCoreApplication.translate("MainWindow", u"Headphones", None))

        self.comboBox_eqonoff.setItemText(0, QCoreApplication.translate("MainWindow", u"Equalizer On", None))
        self.comboBox_eqonoff.setItemText(1, QCoreApplication.translate("MainWindow", u"Equalizer Off", None))

        self.label_2.setText(QCoreApplication.translate("MainWindow", u"31Hz", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"62Hz", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"-9dB", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"0db", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"+9dB", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"+12dB", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"-12dB", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"125Hz", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"250Hz", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"500Hz", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"1kHz", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"2kHz", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"4kHz", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"8kHz", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"16kHz", None))
    # retranslateUi

